// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVzJtch4kptma6m68MGZP6AGtt1h2zy6Q',
    appId: '1:1042135335286:android:a23904679aca4ade9f3a57',
    messagingSenderId: '1042135335286',
    projectId: 'stajyerpro-app',
    storageBucket: 'stajyerpro-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3B0KMQWR3iDQL-yQHGgjwpHgeTLRyxMo',
    appId: '1:1042135335286:ios:fb8c46836df21a9b9f3a57',
    messagingSenderId: '1042135335286',
    projectId: 'stajyerpro-app',
    storageBucket: 'stajyerpro-app.firebasestorage.app',
    iosClientId: '1042135335286-7i3e8bo4pbaheqpagj1itt58jugoh3bu.apps.googleusercontent.com',
    iosBundleId: 'com.stajyerpro.stajyerproApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQCN3pfW7FCR_hR_5Fw2IUZT_oAW-e-IY',
    appId: '1:1042135335286:web:cf6bb9f5c38126b99f3a57',
    messagingSenderId: '1042135335286',
    projectId: 'stajyerpro-app',
    authDomain: 'stajyerpro-app.firebaseapp.com',
    storageBucket: 'stajyerpro-app.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3B0KMQWR3iDQL-yQHGgjwpHgeTLRyxMo',
    appId: '1:1042135335286:ios:fb8c46836df21a9b9f3a57',
    messagingSenderId: '1042135335286',
    projectId: 'stajyerpro-app',
    storageBucket: 'stajyerpro-app.firebasestorage.app',
    iosClientId: '1042135335286-7i3e8bo4pbaheqpagj1itt58jugoh3bu.apps.googleusercontent.com',
    iosBundleId: 'com.stajyerpro.stajyerproApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQCN3pfW7FCR_hR_5Fw2IUZT_oAW-e-IY',
    appId: '1:1042135335286:web:c8f8eb957aae983b9f3a57',
    messagingSenderId: '1042135335286',
    projectId: 'stajyerpro-app',
    authDomain: 'stajyerpro-app.firebaseapp.com',
    storageBucket: 'stajyerpro-app.firebasestorage.app',
  );

}